@url = http://localhost:8080/usuarios


# Cria um novo usuario
POST {{url}} HTTP/1.1
content-type: application/json

{
    "nome":"viniciusZo",
    "nomeUsuario":"vini1394",
    "email":"vinicius1394@gmail.com",
    "senha":"123456"
}

###

# Realiza o login e armazena o token
# @name login
POST {{url}}/login HTTP/1.1
content-type: application/json

{
    "email":"vinicius1394@gmail.com",
    "senha":"123456"
}

> {% 
    response = JSON.parse(response.body);
    token = response.token;
    id - response.idUsuario;
%}

###
@token = {{login.response.body.token}}
@id = {{login.response.body.idUsuario}}

# Busca usuário por id
GET {{url}}/{{id}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### 

# Deletar usuario por ID e body
DELETE {{url}}/{{id}}  HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}} 

{
    "idUsuario":"{{id}}",
    "name":"viniciusZao",
    "username":"vinicius321",
    "email":"vinicius321@gmail.com",
    "superUsuario":"false"
}
